apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-textgen'
  labels:
    katenary.io/component: textgen
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 01034b607ec486ee5d6156eba0ff79f0fc8212af
    katenary.io/version: 2.0.0-beta2
spec:
  selector:
    katenary.io/component: textgen
    katenary.io/release: '{{ .Release.Name }}'
  ports:
    - name: webui
      protocol: TCP
      port: 7860
      targetPort: 7860
    - name: api-stream
      protocol: TCP
      port: 5005
      targetPort: 5005
    - name: api-generate
      protocol: TCP
      port: 5000
      targetPort: 5000
